/*-----------------------------------------------------
FILE: PM_GLOB.H
SUBJ: Basic global variables for HVA's Packet Monitor
HIST: 980206 V0.1
			980418 V0.1 - Added class PM_GLOBAL
-------------------------------------------------------*/

#ifndef PM_GLOB_H
#define PM_GLOB_H

#define __WARN
#define __TRACE

// Define our input mode to compile this version for.
#define PE_ENGINE


#endif    // ifndef PM_GLOB_H
